### ISSUE TITLE
[FEATURE REQUEST] Clone / copy subaccount (with content + settings)

### ISSUE THREAD

**Issue by mar-hol** [SAP-samples/btp-setup-automator#121]
### Which area is mainly impacted

Other

### Requested Feature

There should be a possibility to clone / copy a subaccount with its content (e.g. application) settings. 
Or at least a script to compare BTP subaccounts to see were might be differences in content / configuration.

### Use Case/Scenario

Customers want to move their subaccount from one region to another region (eg from eu10 eu11 for EU access only reasons, or switch of underlying cloud provider aka hyperscaler or for just for testing / validation purposes /spin up a test environment easily). As of now, it is not possible to easily move subaccount from one region to another region or re-create a subaccount out of an existing one. This is a manual "migration" task (thus time consuming and error prone). It would be helpful to build a script / use case where all available settings (enabled services, applications, ...) of subaccount1 is read and subaccount2 is set up based on this.  Sure, there are a lot of things to be considered as the procedure might differ from enabled service / runtime / subaccount settings etc. 

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by rui1610** [comment]
Sounds great and if you want to start with some initial coding, that would be great.
As this is a bigger task I would not be able to work on it. 

So if you can, go ahead and create a branch or a fork to start working on it.

Sounds good?

**Comment by yevgentrukhin** [comment]
You should be able to recreate an account from scratch based on the use case json file, so you can create multiple copies of same subaccount, do you think more than that? like copying data of applications from one subaccount to another? or what's the idea behind?

**Comment by rui1610** [comment]
No further feedback on this request and therefore closing the issue.
