### ISSUE TITLE
[BUG] JSON Parsing for CF Environment

### ISSUE THREAD

**Issue by ilyabelozerovsap** [SAP-samples/btp-setup-automator#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Cloud Foundry setups

### Current Behavior

After the following command the program expects a json with available environments:
```bash
btp --format json list accounts/environment-instances --subaccount 
```
The keys for this JSON can have different format (I suppose for different cloud versions). You already process this difference in helperEnvCF.py (line 38):
```python
            org = labels.get("Org Name:")
            if org is None:
                org = labels.get("Org Name")
```
But not in btp_cli.py (line 380):
```python
                            thisOrgId = labels["Org ID:"]
                            thisOrg = labels["Org Name:"]
```
Which causes an error:
```bash
####################################################################################################
# ERROR
####################################################################################################
  File "/home/user/libs/python/btp_cli.py", line 380, in create_environments
    thisOrgId = labels["Org ID:"]

NoneType: None
```

### Expected Behavior

No error is expected :)

**Comment by rui1610** [comment]
Can you please share the parameters.json and your usecase.json file, so that we can try to reproduce this issue?

**Comment by rui1610** [comment]
Fixed with https://github.com/SAP-samples/btp-setup-automator/pull/124
