### ISSUE TITLE
[BUG] Users are added as Global Account admins

### ISSUE THREAD

**Issue by pirnz** [SAP-samples/btp-setup-automator#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Security

### Current Behavior

Users from the `admin` section of the usecase file are added as:

- Subaccount admins
- Org admins (when using CF)
- Space admins (when using CF)
- Global Account administrators

### Expected Behavior

Users from the `admin` section of the usecase file should be added as:

- Subaccount admins
- Org admins (when using CF)
- Space admins (when using CF)

### Steps To Reproduce

Running any usecase with emails in the `admin` section, the users will be added as Global Account admins.

### Anything else?

The Global Account is the _backend_ of BTP. Admins are able to create subaccounts and assign entitlements. The GA admins should be a small and controlled population.

Adding all users as GA admins shouldn't be the default behavior, as this jeopardizes any effort on keeping the GA admins under control. 

Currently _btp-setup-automator_ doesn't add users as GA admins for trial environments. Could I use this block to add a flag (maybe in parameters?) to choose whether to add users or not? Is there any specific reason for doing this?

Thanks,
Pedro

**Comment by rui1610** [comment]
The "admins" section in the usecase file is no longer supported. Can you check if you are using the latest container image?

**Comment by pirnz** [comment]
Hi,
Thank you for pointing me to the obvious.
The latest version has taken care of this already.

Pedro
