### ISSUE TITLE
[FEATURE REQUEST] Enable Subscription of own applications

### ISSUE THREAD

**Issue by AlexRieder** [SAP-samples/btp-setup-automator#178]
### Which area is mainly impacted

Configuration

### Requested Feature

Currently it is only possible to subscribe to applications which are listed as entiltments in the global account. In cases where there is an own application deployed which can be subscribed from within that global account the usecase check that happens in the beginning will fail. 
It would be good if the we could decide per serivce/application if that should be taken into account for the prerequisites check. 

### Use Case/Scenario

In our scenario we would like to subacribe to an application that has been deployed by a previous run of the setup automator. With that we can completely automate the setup of a multitenancy application including the creation of a consumer subaccount and the subscription to the application. 

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by lechnerc77** [comment]
Hi Alex,

can you provide more details and example usecases for this setup? From the top of my head I would assume that some adoptions are needed in the btpsa as this is not a service registered at the service manager right? But would like to validate that on a dedicated example.

**Comment by AlexRieder** [comment]
Hi @lechnerc77 , 

the general idea is to call the usecase after we have setup and deployed our kyma application. With the second usecase which is attached we want to create a second subaccount where we subscribe that application. The application is registered in the saas registry on global account level (not at the service manager as it's not a service). 

You can test it on this global account with the subaccount btp-setup-test: 
https://cockpit.eu10.hana.ondemand.com/cockpit/#/globalaccount/2505dea8-1524-4e5f-924e-276483596166/subaccount/4dd99aac-238c-43ea-9d8c-32472e8816e5/subaccountoverview

The usecase can be executed with the following command: 
./btpsa -usecasefile 'attached usecase' -globalaccount easyfranchise -myemail <email> -subaccountname btp-automator-test  -region eu10

[usecase-consumer.txt](https://github.com/SAP-samples/btp-setup-automator/files/9063620/usecase-consumer.txt)

If you run into problem let me know. 

Thanks 
Alex

**Comment by lechnerc77** [comment]
@AlexRieder : Thanks for the additional info. I see where the issues comes from, now just need to find a clever way to resolve it :-)

**Comment by lechnerc77** [comment]
Status Quo: branch [custom-apps](https://github.com/SAP-samples/btp-setup-automator/tree/custom-apps) contains the enhancements for the request.

ToDo:

- Regression test
- Enhancement of documentation

**Comment by lechnerc77** [comment]
Documentation is updated, Docker image is built and available
