### ISSUE TITLE
[FEATURE REQUEST] Could add new changes in a new branch?

### ISSUE THREAD

**Issue by JavierRodriguezPrieto** [SAP-samples/btp-setup-automator#185]
### Which area is mainly impacted

Docker Image (Build or Run)

### Requested Feature

Hello,

But we're trying to use it and we can check that is appearing different errors when you add new changes (currently we have an issue in a python file). This is a problem because  when we're trying to use and is appearing different errors. Could be possible create a stable branch which all working and new changes in another different branch?

Thanks

### Use Case/Scenario

Its using the image from docker

http://ghcr.io/sap-samples/btp-setup-automator:main

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by lechnerc77** [comment]
New functional changes are usually developed in a branch, tested and then merged. 
The provided Docker image represents a stable state. However, we had a bug in the JSON schema yesterday, that was fixed as soon as we got aware.

If you face an error , please open a issue with the corresponding information (e.g. which file gives you an error)
