### ISSUE TITLE
[FEATURE REQUEST] Issues with new accounts registered under SAP Universal ID

### ISSUE THREAD

**Issue by raiatdeloitte** [SAP-samples/btp-setup-automator#188]
### Which area is mainly impacted

CLI in general

### Requested Feature

New users registered for a SAP BTP trial account are registered using the SAP Universal ID which causes the execution of the btpsa script to fail authentication. The feature to be requested would be that the SAP Universal ID users are able to login when using the script to run the automation.

### Use Case/Scenario

I have just created a new SAP BTP trial user in order to do some testing with the SAP BTP setup automator and this user has been created using the SAP Universal ID. 

When running the SAP BTP automator the BTP account credentials are failing due to my user being linked to the SAP Universal ID. I have seen that this is due to the underlying CLI not supporting it in a background mode. An option exists that would prompt a web browser by specifying -sso manual but after trying that one on console it doesn't seem to work either.

I guess this is more of a CLI issue but if al new users on SAP BTP trial are going to be linked to the SAP Universal ID then this can be a blocker for the setup automator as the login process on the image and the btpsa script will fail to authenticate.

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by raiatdeloitte** [comment]
Hi Rui,

Not so far. We are starting a new project and building a CI/CD pipeline using the BTP setup automator for dev so far. Being more accurate, I’m generating a template that will apply to all different environments.

In order to progress I have changed to a different account that I had which is not linked to the SAP Universal ID but it’s also a trial account. We will shortly get the project’s BTP account which won’t be trial and we will test there too.

Kind regards,
Ibai

From: Rui Nogueira ***@***.***>
Sent: lunes, 11 de julio de 2022 17:39
To: SAP-samples/btp-setup-automator ***@***.***>
Cc: Ramos Astola, Ibai ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [SAP-samples/btp-setup-automator] [FEATURE REQUEST] Issues with new accounts registered under SAP Universal ID (Issue #188)


Thanks for the feedback @raiatdeloitte<https://secure-web.cisco.com/1-UWa0EmZVhFvKW0JcTaqULdv_l6dGai_0HzK7e_IPAKn_A8xaikhEKg8p9XCPb2GKJi46kEiyP8coi-xUnjwlMpkLUiWUTyKYORsgMksDwl64rNP458hA_6tOuEkQdhTRm_JNa0gq9OCKL7CokJOtUW3KSLx2UgoAUPeW88P7qbGAaOv7FQpZJc_7GSo-dLlqzdVFjooSV2jPWr8JNJgzZ3Q0nZBfdlRiJ1iN12MuQTHivlxEqQ72e0i9CIhGnonKhzOEkcCmudb0uAbCCJ15JpGxBNIX9D7mPJVGDIJ9OLfcYpAJaknfjBZTh9Wp6_B/https%3A%2F%2Fgithub.com%2Fraiatdeloitte> . Did you try out the btp-setup-automator on a productive SAP BTP account and had the same issue?

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1yN7OupvJTLv0u_njCOArYA4Z1fJZXGYq05sUVf5uQ5jRiR5o3MKyokwj2saEy3q4DVrJN0lvyFUs51_ySK1FiL_gM38CpNttDowS0ah1tjszEabeKswF3ct3OeexDdd-BY6kTckHUW2EdeDHAnUD9qXovkIFG7XlCnNE2q7L7OxI0MFUXzCMrPr5tObiq208UObp6I6Uq7qa8dcGLW0y84XnK-0IXG5-P-XlQ3nKmrmcvgUVF81tqw4wDgod38yAJYYrB04hVxhPXsQrqcrSo1sg_HeQuxOCOB1dLR-cMGn4s-ebSaasFftqVZBJ4oM2/https%3A%2F%2Fgithub.com%2FSAP-samples%2Fbtp-setup-automator%2Fissues%2F188%23issuecomment-1180566424>, or unsubscribe<https://secure-web.cisco.com/1HZYKiwb3NOZVnFp7Us9sBEc3h7MwN3UvyYrrvlvOa4eIOS3Y43vuvWWVH2lI4anny6qIr4BRHpirDN8eKYu5AFxuI0KSZH3z7c4psuRlvUi0RKhJ1z4KQhnMjmOoEljdLb6t9SZZpGD_6OulkqiFin7dJ2V1xxZNh2UtArBEL9HtSSKH85pggXonqs-Sthz9rKNXQO0c_6gvK3hHNSm9XhtFDfqJXvnaY7j9tufMFRp7EfRe4GSxsg5rVmIUlaGHGIscMAHJBxI31rj61k6XIU4iTfOkmN5OO7ghO9N5lFD-LBUBIn57dAA64iJ2qmnF/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2ACWXELC7VB63CDJH2VSPTVTQ52VANCNFSM53GPG2KQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>





--------------------------------------------------------

ADVERTENCIA LEGAL

Este mensaje va dirigido, de manera exclusiva, a su destinatario y contiene información confidencial y sujeta al secreto profesional, cuya divulgación no está permitida por la ley. En caso de haber recibido este mensaje por error, le rogamos que, de forma inmediata, nos lo comunique mediante correo electrónico remitido a nuestra atención o a través del teléfono (+ 34) 91 514 50 00 y proceda a su eliminación, así como a la de cualquier documento adjunto al mismo. Asimismo, le comunicamos que la distribución, copia o utilización de este mensaje, o de cualquier documento adjunto al mismo, cualquiera que fuera su finalidad, están prohibidas por la ley.

Le informamos, como destinatario de este mensaje, que el correo electrónico y las comunicaciones por medio de Internet no permiten asegurar ni garantizar la confidencialidad de los mensajes transmitidos, así como tampoco su integridad o su correcta recepción, por lo que el emisor no asume responsabilidad alguna por tales circunstancias. Si no consintiese en la utilización del correo electrónico o de las comunicaciones vía Internet le rogamos nos lo comunique y ponga en nuestro conocimiento de manera inmediata.

Deloitte se refiere a Deloitte Touche Tohmatsu Limited, (prívate company limited by guarantee, de acuerdo con la legislación del Reino Unido) y a su red de firmas miembro, cada una de las cuales es una entidad independiente. En www.deloitte.com/about<http://www.deloitte.com/about> se ofrece una descripción detallada de la estructura legal de Deloitte Touche Tohmatsu Limited y sus firmas miembro.

--------------------------------------------------------

PRIVILEGED AND CONFIDENTIAL

This message is intended exclusively for the person to whom it is addressed and contains privileged and confidential information protected from disclosure by law. If you are not the addressee indicated in this message, you should immediately delete it and any attachments and notify the sender by reply e-mail or by phone (+ 34 91 514 50 00). In such case, you are hereby notified that any dissemination, distribution, copying or use of this message or any attachments, for any purpose, is strictly prohibited by law.

We hereby inform you, as addressee of this message, that e-mail and Internet do not guarantee the confidentiality, nor the completeness or proper reception of the messages sent and, thus, the sender does not assume any liability for those circumstances. Should you not agree to the use of e-mail or to communications via Internet, you are kindly requested to notify us immediately.

Deloitte refers to one or more of Deloitte Touche Tohmatsu Limited, a UK private company limited by guarantee, and its network of member firms, each of which is a legally separate and independent entity. Please see www.deloitte.com/about<http://www.deloitte.com/about> for a detailed description of the legal structure of Deloitte Touche Tohmatsu Limited and its member firms.

**Comment by raiatdeloitte** [comment]
Hi,

It’s ok with me as I was able to bypass in this scenario but up to you in case you think this feature is a must going ahead for people that can’t bypass. Right now I would not be able to collaborate due to work load but just thinking on more tranquil times, contributions are in python, are they?

Kind regards,
Ibai





--------------------------------------------------------

ADVERTENCIA LEGAL

Este mensaje va dirigido, de manera exclusiva, a su destinatario y contiene información confidencial y sujeta al secreto profesional, cuya divulgación no está permitida por la ley. En caso de haber recibido este mensaje por error, le rogamos que, de forma inmediata, nos lo comunique mediante correo electrónico remitido a nuestra atención o a través del teléfono (+ 34) 91 514 50 00 y proceda a su eliminación, así como a la de cualquier documento adjunto al mismo. Asimismo, le comunicamos que la distribución, copia o utilización de este mensaje, o de cualquier documento adjunto al mismo, cualquiera que fuera su finalidad, están prohibidas por la ley.

Le informamos, como destinatario de este mensaje, que el correo electrónico y las comunicaciones por medio de Internet no permiten asegurar ni garantizar la confidencialidad de los mensajes transmitidos, así como tampoco su integridad o su correcta recepción, por lo que el emisor no asume responsabilidad alguna por tales circunstancias. Si no consintiese en la utilización del correo electrónico o de las comunicaciones vía Internet le rogamos nos lo comunique y ponga en nuestro conocimiento de manera inmediata.

Deloitte se refiere a Deloitte Touche Tohmatsu Limited, (prívate company limited by guarantee, de acuerdo con la legislación del Reino Unido) y a su red de firmas miembro, cada una de las cuales es una entidad independiente. En www.deloitte.com/about<http://www.deloitte.com/about> se ofrece una descripción detallada de la estructura legal de Deloitte Touche Tohmatsu Limited y sus firmas miembro.

--------------------------------------------------------

PRIVILEGED AND CONFIDENTIAL

This message is intended exclusively for the person to whom it is addressed and contains privileged and confidential information protected from disclosure by law. If you are not the addressee indicated in this message, you should immediately delete it and any attachments and notify the sender by reply e-mail or by phone (+ 34 91 514 50 00). In such case, you are hereby notified that any dissemination, distribution, copying or use of this message or any attachments, for any purpose, is strictly prohibited by law.

We hereby inform you, as addressee of this message, that e-mail and Internet do not guarantee the confidentiality, nor the completeness or proper reception of the messages sent and, thus, the sender does not assume any liability for those circumstances. Should you not agree to the use of e-mail or to communications via Internet, you are kindly requested to notify us immediately.

Deloitte refers to one or more of Deloitte Touche Tohmatsu Limited, a UK private company limited by guarantee, and its network of member firms, each of which is a legally separate and independent entity. Please see www.deloitte.com/about<http://www.deloitte.com/about> for a detailed description of the legal structure of Deloitte Touche Tohmatsu Limited and its member firms.

**Comment by Adrian-Melero** [comment]
Hello,
I´m getting the same issue with my btp trial account. It´s linked to SAP Universal ID by default and it looks like it´s not possible to make a successful login with this type of account.

**Comment by lechnerc77** [comment]
As we use BTP CLI under the hood, we must also check [SAP Note 3085908](https://launchpad.support.sap.com/#/notes/3085908). According to it BTP CLI does not yet support SAP Universal ID

**Comment by Adrian-Melero** [comment]
Thanks, that worked like a charm

**Comment by lechnerc77** [comment]
I close this issue as there is nothing we can do (from `btpsa` implementation perspective) to improve the situation due to the dependency to the BTP CLI. I recorded the situation and the workaround in a [discussion](https://github.com/SAP-samples/btp-setup-automator/discussions/388), so that other user stumbling across the situation know how to deal with it.
