### ISSUE TITLE
[FEATURE REQUEST] Reference between defined service resources

### ISSUE THREAD

**Issue by raiatdeloitte** [SAP-samples/btp-setup-automator#194]
### Which area is mainly impacted

Cloud Foundry setups

### Requested Feature

While considering the usage of the btp setup automator in a project the following situation showed up. There is maybe a way to achieve this I'm missing but take this as a possible suggestion.

On the scenario I'm building I will instantiate a SAP launchapd service to host some site. I would want to also use the Cloud Transport Management service. I have created instances for both the Launchpad and the Cloud Transport Management in my use case. When creating the Cloud Transport Management service I generate a service key that will be required in a ctms_destination destination that needs to be setup.

I also create the destination in the use case but I would need to reference the service key credentials from the service key that gets generated when instantiating the Cloud Transport Management service. Is there a way to reference artifacts generated on another service on the description of another service in the use case? What I'd be thinking of would be that the use case references the service key parameters from an object that is generated in a previous step., in this case referencing the service key that gets generated in the Cloud Transport Management service in a destination that gets generated at a later stage in the same use case.

### Use Case/Scenario

{
  "aboutThisUseCase": {
    "name": "Setup CF Environment Example",
    "description": "This use case serves to show an example of need to reference service attributes from another service",
    "author": "raiatdeloitte",
    "testStatus": "to be tested",
    "usageStatus": "IN DEVELOPMENT",
    "relatedLinks": [
    ]
  },
  "services": [
    {
      "name": "SAPLaunchpad",
      "plan": "standard",
      "category": "APPLICATION"
    },
    {
      "name": "transport",
      "plan": "standard",
      "category": "SERVICE",
      "createServiceKeys": [
        "transport-ServiceKey" **// This line is the one generating a service key**
      ]
    },
    {
      "name": "destination",
      "plan": "lite",
      "category": "SERVICE",
      "parameters": {
        "cfspacename":"$cf_space",
        "HTML5Runtime_enabled": "true",
        "init_data": {
          "subaccount": {
            "existing_destinations_policy": "fail",
            "destinations": [
              {
                "Name": "cmts_destination",
                "Type": "HTTP",
                "URL": "http://sap.com",
                "tokenServiceURL": "/oauth/token",
                "Authentication": "OAuth2ClientCredentials",
                "ProxyType": "Internet",
                "Description": "Cloud Transport Management destination",
                "clientId": "transport-sk-user", **// I'd like to be able to reference the result of the execution of the generation of transport-ServiceKey here**
                "clientSecret": "transport-sk-pass", **// I'd like to be able to reference the result of the execution of the generation of transport-ServiceKey here**
                "tc.languages": "en-GB,es-ES"
              }
            ]
          }
        }
      }
    }
  ]
}

### Would you like to support us?

- [ ] Yes, I would like to support you

### Anything else?

Take this as a suggestion of a nice to have. Not saying it should be implemented right away or as proposed. Also, maybe it's already possible and I missed the point.

**Comment by rui1610** [comment]
Hi @raiatdeloitte , have you considered using the **executeAfterAccountSetup** attribute in the usecase.json file and combining it with the collected data in the log file **metadata_log.json**?
That should bring you already a few steps further. But as long as you won't be able to contribute it will be difficult to address your feature request in a timely manner.
For now, I'll keep this request open. Thanks for your request!

**Comment by lechnerc77** [comment]
No feedback since 15th of July, so I will close this issue. If the request is still relevant, please re-open the issue
