### ISSUE TITLE
[BUG] Not able to add entitlement of cloudfoundry MEMORY Plan

### ISSUE THREAD

**Issue by shivakumar-p12-sap** [SAP-samples/btp-setup-automator#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

There was a issue which looks similar(https://github.com/SAP-samples/btp-setup-automator/issues/28) but this is little different. 

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Cloud Foundry setups

### Current Behavior

Getting the below error when i tried to add the entitlement.

![image](https://user-images.githubusercontent.com/96462457/191774779-6953d27e-5ffb-4675-b64a-d99f8dc93fee.png)

### Expected Behavior

Able to add entitlement for cloudfoundry MEMORY plan 
![image](https://user-images.githubusercontent.com/96462457/191776217-3b6cb2ed-edd3-45b0-aa79-a367ef0753db.png)

also able to set the number of MEMORY units to it
![image](https://user-images.githubusercontent.com/96462457/191776445-e26c8990-c25b-4d12-9053-476e15981180.png)

### Steps To Reproduce

Please run this usecase file by adding your email id in admins
`
{
  "aboutThisUseCase": {
      "name": "Setup the account for riskmanagement scenario execution",
      "description": "This will create subaccount and add required entitlement",
      "author": "EMAIL@sap.com",
      "testStatus": "tested successfully",
      "usageStatus": "READY TO BE USED",
      "relatedLinks": [
          "https://pages.github.tools.sap/CPES/CPAppDevelopment/"
      ]
  },
  "admins": ["YOUR_EMAIL_ID" ],
  "services": [
    {
      "name": "cloudfoundry",
      "plan": "standard",
      "category": "ENVIRONMENT"
      },
      {
        "name": "cloudfoundry",
        "plan": "MEMORY",
        "category": "SERVICE",
        "entitleonly": true
        }
  ], 

"assignrolecollections": [
  {
      "name": "Global Account Administrator",
      "type": "account",
      "level": "global account",
      "assignedUserGroupsFromParameterFile": [
          "admins"
      ]
  },
  {
      "name": "Subaccount Administrator",
      "type": "account",
      "level": "sub account",
      "assignedUserGroupsFromParameterFile": [
          "admins"
      ]
  },
  {
      "name": "Subaccount Service Administrator",
      "type": "account",
      "level": "sub account",
      "assignedUserGroupsFromParameterFile": [
          "admins"
      ]
  },
  {
      "name": "SpaceManager",
      "type": "cloudfoundry",
      "level": "space",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "developers"
      ]
  },
  {
      "name": "SpaceDeveloper",
      "type": "cloudfoundry",
      "level": "space",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "developers"
      ]
  },
  {
      "name": "SpaceAuditor",
      "type": "cloudfoundry",
      "level": "space",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "developers"
      ]
  },
  {
      "name": "OrgManager",
      "type": "cloudfoundry",
      "level": "org",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "testers"
      ]
  },
  {
      "name": "OrgAuditor",
      "type": "cloudfoundry",
      "level": "org",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "auditors"
      ]
  }
]
}
`

### Logs and configuration files available?

parameters.json

`{
  "usecasefile": "usecases/inDevelopment/risk_management.json",
  "region": "eu12",
  "globalaccount": "GLOBAL_ID",
  "btpcliapihostregion":"sap",
  "myemail": "YOUR_EMAIL_ID",
  "loginmethod": "sso",
  "subaccountname": "rmexecution",
  "envvariables": {
  }
}`

usecase.json

`
{
  "aboutThisUseCase": {
      "name": "Setup the account for riskmanagement scenario execution",
      "description": "This will create subaccount and add required entitlement",
      "author": "EMAIL@sap.com",
      "testStatus": "tested successfully",
      "usageStatus": "READY TO BE USED",
      "relatedLinks": [
          "https://pages.github.tools.sap/CPES/CPAppDevelopment/"
      ]
  },
  "admins": ["YOUR_EMAIL_ID" ],
  "services": [
    {
      "name": "cloudfoundry",
      "plan": "standard",
      "category": "ENVIRONMENT"
      },
      {
        "name": "cloudfoundry",
        "plan": "MEMORY",
        "category": "SERVICE",
        "entitleonly": true
        }
  ], 

"assignrolecollections": [
  {
      "name": "Global Account Administrator",
      "type": "account",
      "level": "global account",
      "assignedUserGroupsFromParameterFile": [
          "admins"
      ]
  },
  {
      "name": "Subaccount Administrator",
      "type": "account",
      "level": "sub account",
      "assignedUserGroupsFromParameterFile": [
          "admins"
      ]
  },
  {
      "name": "Subaccount Service Administrator",
      "type": "account",
      "level": "sub account",
      "assignedUserGroupsFromParameterFile": [
          "admins"
      ]
  },
  {
      "name": "SpaceManager",
      "type": "cloudfoundry",
      "level": "space",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "developers"
      ]
  },
  {
      "name": "SpaceDeveloper",
      "type": "cloudfoundry",
      "level": "space",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "developers"
      ]
  },
  {
      "name": "SpaceAuditor",
      "type": "cloudfoundry",
      "level": "space",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "developers"
      ]
  },
  {
      "name": "OrgManager",
      "type": "cloudfoundry",
      "level": "org",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "testers"
      ]
  },
  {
      "name": "OrgAuditor",
      "type": "cloudfoundry",
      "level": "org",
      "assignedUserGroupsFromParameterFile": [
          "admins",
          "auditors"
      ]
  }
]
}`

**Comment by rui1610** [comment]
Hi @shivakumar-p12-sap , 
we've analyzed your issue.

In the [btpsa-usecase.json](https://github.com/SAP-samples/btp-setup-automator/blob/main/libs/btpsa-usecase.json) there is no MEMORY plan for cloudfoundry available inside btpsa.

The btp-setup-automator focuses on the usage of the SAP Business Technology Platform by customers. You might be trying to access a plan, which is only available for SAP teams and/or SAP partners.
