### ISSUE TITLE
[BUG] Container Build fails on WSL - home directory not created?

### ISSUE THREAD

**Issue by dzett** [SAP-samples/btp-setup-automator#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Docker Image (Build or Run)

### Current Behavior

Executing the run script on WSL fails during container build with:

```
...

Step 52/71 : RUN cf install-plugin -f https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/latest/download/multiapps-plugin.linux32
---> Running in 69edce9a1520
mkdir /home/user/.config: permission denied
FAILED
The command '/bin/sh -c cf install-plugin -f https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/latest/download/multiapps-plugin.linux32' returned a non-zero code: 1
...
```

### Expected Behavior

Build works fine.

### Steps To Reproduce

On WSL2 on Windows, run the ./run script

### Anything else?

I noticed that the dockerfile executes [adduser with option --no-create-home](https://github.com/SAP-samples/btp-setup-automator/blob/main/config/Dockerfile#L108), and also didn't find any other instruction that would create the home directory.

I removed the --no-create-home option and afterwards the run script worked fine, is there a reason to not create a home directory for the "user"-user?

**Comment by rui1610** [comment]
Hi @dzett , we were able to reproduce the issue. In essence the **no-create-home** option was not needed as we create the folder manually.

We have fixed this in the code and as well created a new docker image in this GitHub repo.

Please let us know in case this works for you, and we can close the issue.

Best,
Rui

**Comment by dzett** [comment]
Hi @rui1610, I confirm the container is now working in my WSL2 setup in principle and I can launch the btpsa command inside. Thanks for the quick fix! D.
