### ISSUE TITLE
[FEATURE REQUEST] Move "admins" from usecase to parameters file

### ISSUE THREAD

**Issue by rui1610** [SAP-samples/btp-setup-automator#27]
### Which area is mainly impacted

Configuration

### Requested Feature

Currently the admins section is defined in the usecase configuration. This should be modified.

The usecase configuration should be rather independent from the actual user calling the use case. Therefore, it makes more sense to have the admins section inside the parameters.json file.

### Use Case/Scenario

This request applies to all use cases.

### Would you like to support us?

- [X] Yes, I would like to support you

### Anything else?

I've already started do develop the change and will send a pull request soon.

**Comment by rui1610** [comment]
But please add your comments on this idea.

**Comment by yevgentrukhin** [comment]
What is the main reason to move admins into parameter file?

At this moment I'm satisfied how admin user management is done.

As we discussed internally, this was proposed vision for the use case but we had not time to implement this:
"requiredrolecollections": [
    {
        "name": "BPM Administrator",
        "roles": [
            {"name": "BPMADmin", "roletemplate": "RuleRepositorySuperUser"},
            {"name": "BPMADmin2", "roletemplate": "RuleRepositorySuperUser"}
        ],
        "assignedUserGroups": ["adminsForApp","superheros"]
    }
],
"userGroups": [
    {"name": "adminsSubaccount","type": "subaccount", "members": ["john@test.com", "jane@test.com"]},
    {"name": "adminsForApp","type": "custom", "members": ["john@test.com", "jane@test.com"]},
    {"name": "superheros","type": "custom", "members": ["tony@stark.com","captain@america.com"]}
]

**Comment by rui1610** [comment]
I've given this some additional thoughts. I think we should move ahead with the initial plan you've sketched above. Do you want to give it a first try in the code? I'm not sure whether I'll have time to code this myself in the next couple of weeks.

**Comment by yevgentrukhin** [comment]
Yes, i like this approach but i dont have capacity at the moment, maybe, let's come to this one in couple of weeks.

**Comment by pirnz** [comment]
Hi,

It makes sense to keep subaccount resources (services, environments) separate from subaccount parameters (subaccount name, admins).

I have a use case where the subaccount has a number suffix, and the admin email also has the same number suffix. Currently I have to modify the two files (through a script). With this change, I would only have to deal with the parameters, while the usecase can remain constant.

Kr,
Pedro

**Comment by rui1610** [comment]
This issue has now been fixed with this pull request: https://github.com/SAP-samples/btp-setup-automator/pull/109
