### ISSUE TITLE
[BUG] Entitlement servicePlan can differ from provisioning servicePlan

### ISSUE THREAD

**Issue by Rand0mF** [SAP-samples/btp-setup-automator#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which area is mainly impacted

CLI in general

### Current Behavior

When adding redis with the plan `v4.0-dev` the btpsa will print this error:

![image](https://user-images.githubusercontent.com/99967423/159002782-1313049b-fa8b-4d3f-badf-c22ee43de80c.png)

I think this is because the provisioning for this plan needs an entitlement of another plan: 'dev'

When trying with the plan 'dev' the btpsa can run and manage the entitlement successfully but fails at the service creation (obviously)
![image](https://user-images.githubusercontent.com/99967423/159003332-a2e224a3-236d-4fde-b247-11867b5d7a17.png)

The command works with cf cli `cf create-service redis v4.0-dev test-redis`

### Expected Behavior

If a service with plan `v4.0-dev` is to be provisioned, btpsa should figure out that the related entitlement servicePlan is `dev`.

### Steps To Reproduce

1. run the script at any environment with redis assignment on the globalaccount
2. add this config to the usecase
```
"services": [
    {
      "category": "SERVICE",
      "name": "redis",
      "plan": "v4.0-dev",
      "instancename": "test-redis"
    }
  ],
```

**Comment by rui1610** [comment]
As the error message stated, **redis** is not available with the plan **v4.0-dev** in the region **eu10**.

I've just checked in my global account, and could not find any "v4.0-dev" service plan (in region us10). Try running the following command - as shown in your log file - and see which service plans are available. That's what the btp-setup-automator is doing:

`btp --format json list accounts/entitlement --global-account YOURGLOBALACCOUNTSUBDOMAIN`

If you find there a service plan for the eu10 region, please let us know here.

**Comment by rui1610** [comment]
Can you please attach your parameters.json and usecase.json file in here, so I can better analyze? I'll try out on my machine with your settings. Please remove any passwords from the files in case you added them somewhere.

**Comment by rui1610** [comment]
To explain a bit further: the script uses the btp CLI to determine which service plans are available for each service that your global account is entitled for. So if it works in the CF CLI, it doesn't solve the issue that the btp CLI doesn't detect the service plan.

Therefore, you'd need to share your parameters.json and your usecase.json file, so that we can analyze whether this is an issue in the btp CLI or in the btp-setup-automator.

**Comment by Rand0mF** [comment]
parameters:
```json
{
  "usecasefile": "usecases/released/cap_app_launchpad_TRIAL.json",
  "region": "eu10",
  "globalaccount": "7974ff10-95fe-4bfd-b97a-d3f52f5b44cd",
  "myemail": "armin.kramer@sap.com",
  "loginmethod": "sso",
  "subaccountname": null,
  "orgid": null,
  "cfspacename": "development",
  "suffixinstancename": null,
  "iashost": null
}
```
usecase:
```json
{
  "aboutThisUseCase": {
    "name": "Deploy full-stack CAP application running in SAP Launchpad (on SAP BTP TRIAL account)",
    "description": "This usecase provides all necessary information to create the necessary service instances and app subscription for a CAP application and to deploy that application on a SAP BTP account.",
    "author": "rui.nogueira@sap.com",
    "testStatus": "tested successfully",
    "usageStatus": "READY TO BE USED",
    "relatedLinks": [
      "https://developers.sap.com/tutorials/btp-app-launchpad-service.html"
    ]
  },
    "services": [
    {
      "category": "SERVICE",
      "name": "redis",
      "plan": "v4.0-dev",
      "instancename": "test-redis"
    }
  ],
  "executeAfterAccountSetup": [
  ],
  "executeToPruneUseCase": [
  ]
}
```

**Comment by rui1610** [comment]
As written above the BTP CLI is the tool that "tells" the tool which services and service plans are available for your global account. If you look into the log file this is the command that is used to fetch that information:

`btp --format json list accounts/entitlement --global-account XXXXXX`

I ran that command for my account, and I've looked into the service plans for redis. The only service plans that I saw are called `large`, `medium`, `small`, `xsmall`. The service plan that you have provided in the usecase.json file is called `v4.0-dev`. So my assumption is, that this service-plan is not visible to the btp CLI that the btp-setup-automator is using.

To confirm, can you please run the following command within the container image and let me know whether you found the `v4.0-dev` service plan for `redis`? The command will pipe the command output into a file called `servicelist.json`:

`btp --format json list accounts/entitlement --global-account 7974ff10-95fe-4bfd-b97a-d3f52f5b44cd > servicelist.json`

**Comment by Rand0mF** [comment]
Hi @rui1610 
You can find the mapping with this command: 
`btp --format json list services/plan --environment cloudfoundry --subaccount subaccountId > output.json`. 
API documentation can be found here: https://api.sap.com/api/APIServiceManagment/resource (/v1/service_plans).
However, there is a race condition. You will only get information about service plans already assigned to the subaccount.
![image](https://user-images.githubusercontent.com/99967423/159899270-418425fa-e9bb-40cd-a76d-db90e6e4fced.png)

**Comment by rui1610** [comment]
This issue was addressed in the PR https://github.com/SAP-samples/btp-setup-automator/pull/33 and was merged into the main branch.

I've added a usecase.json file at https://github.com/SAP-samples/btp-setup-automator/blob/main/usecases/other/inDevelopment/redis.json where you can see you how to use the newly introduced service parameter `planCatalogName`.

**Can you please test, as I don't have a global account that I can use to reproduce the issue?**
