### ISSUE TITLE
[FEATURE REQUEST] need tool 'jq' installed in container

### ISSUE THREAD

**Issue by yevgentrukhin** [SAP-samples/btp-setup-automator#29]
### Which area is mainly impacted

Docker Image (Build or Run)

### Requested Feature

We need to have jq as well in container, it will help manipulating btp cli commands and parsing json output. It could be used for debugging or development purposes.

### Use Case/Scenario

debugging/development

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by rui1610** [comment]
Like the idea. Let me check the impact on the size of the container image.

**Comment by rui1610** [comment]
Done :-)
