### ISSUE TITLE
[FEATURE REQUEST] GitLab token support for remote parameters.json and usecase.json files

### ISSUE THREAD

**Issue by hschaefer123** [SAP-samples/btp-setup-automator#310]
### Which area is mainly impacted

Cloud Foundry setups

### Requested Feature

It would be great, to get support for private **GitLab** repos to fetch relevant json files, like this:

```bash
./btpsa \
    -gitlabtoken 'abce....' \
    -parameterfile 'https://git.custom.domain/path/-/raw/main/parameters.json' \
   .....
```
to pass an a GitLab token, which will be used for relevant authentication.

The same token should also be used for eading the usecase, that is defined the same way inside ```parameters.json``` like:

```json
{
   "$schema": "https://raw.githubusercontent.com/SAP-samples/btp-setup-automator/main/schemas/btpsa_parameters.json",
   "usecasefile": "https://git.custom.domain/path/-/raw/main/usecases/my-usecase.json",
   ...
}
```

### Use Case/Scenario

Using it this way, we can reuse the ```parameters.json``` and ```usecase.json``` file to easily automate and create CF subaccounts the following way:

```bash
accountname=new-subaccount-name
./btpsa \
    -gitlabtoken 'abce....' \
    -parameterfile 'https://git.custom.domain/path/-/raw/main/parameters.json' \
    -myemail 'm.musterman@domain.de' \
    -subaccountname $accountname \
    -subdomain $accountname \
    -org $accountname
```

So right after starting docker, we just need the command line call and everthing else will be read from gitlab.

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by lechnerc77** [comment]
Hi @hschaefer123 ,

I just checked the GitLab documentation and the authentication of GitLab. If I understand the documentation correctly the authentication needs to pass the token via the HTTP header in the field `"PRIVATE-TOKEN: <YOUR-TOKEN>"`.
This is very special as usually this information is provided via `"Authorization: Bearer <YOUR-TOKEN>" `
Is my understanding correct?   

Best Christian

**Comment by hschaefer123** [comment]
Hi @lechnerc77,

i just gave it a try to find the solution using gitlab token and v4 api.

Using 

```
GET https://company.git.de/api/v4/projects/1234/repository/files/parameters.json/raw?ref=main
PRIVATE-TOKEN: ...abc...
```

i was able to read the file content (blob) directly.

The raw link itself does not work with token, so i had to use the api.

Best regards
Holger

**Comment by lechnerc77** [comment]
Hi @hschaefer123 ,

the issue I am facing is that this authentication handling seems to be very special for GitLab. Handling over the token via the header is from my experience done via the field "Authorization". 
Extending the authentication flow for fetching the data would follow that approach i.e. I would trigger a request like:

```shell
GET https://company.git.de/api/v4/projects/1234/repository/files/parameters.json/raw?ref=main
Authorization: Bearer <YOUR-TOKEN>
```

However, this would not solve your problem, if I am not mistaken. 

Best,
Christian

**Comment by lechnerc77** [comment]
Hi Holger, 

that's good, I have to make an enhancement to make it work. I let you know once this is part of the dev branch

Best
Christian

**Comment by lechnerc77** [comment]
Available in Dev branch, will be part of release 1.2.0

**Comment by lechnerc77** [comment]
@hschaefer123 You can give things try on the **dev** branch ().
The statement fitting your setup probably is:

```bash
btpsa -parameterfile 'https://WHEREVER/YOUR/FILES/ARE/parameters.json' -externalConfigAuthMethod 'token' -externalConfigToken '<YOUR TOKEN>'
```

**Comment by lechnerc77** [comment]
Close issue - [release 1.2.0](https://github.com/SAP-samples/btp-setup-automator/releases/tag/btpsa-v1.2.0) is available.
Docker Image is updated (`docker pull ghcr.io/sap-samples/btp-setup-automator:btpsa-v1.2.0`)
