### ISSUE TITLE
[FEATURE REQUEST] Support of parameters when subscribing to applications

### ISSUE THREAD

**Issue by lechnerc77** [SAP-samples/btp-setup-automator#313]
### Which area is mainly impacted

CLI in general

### Requested Feature

The btpsa should be enhanced to support parameters when subscribing to applications. Currently parameters are only supported for service instances, but this is also needed for some applications like Cloud Identity Service.

### Use Case/Scenario

Creation of a Cloud Identity Instance via BTP-Setup-Automator (prerequisite for SAP Build Apps)

### Would you like to support us?

- [X] Yes, I would like to support you

### Anything else?

See: <https://help.sap.com/docs/BTP/btp-cli/btp-subscribe-accounts-subaccount.html> - optional parameter --parameters JSON

**Comment by lechnerc77** [comment]
Tasks:

- [ ] Enhancement of btpsa usecase file including schema to support parameters for applications (in analogy to services)
- [ ] Enhancement of btpsa code base for usage of parameters

**Comment by rui1610** [comment]
Implemented enhancement of btpsa code base so that app subscriptions can provide parameters as well.

**Comment by rui1610** [comment]
The issue has been fixed. Can be closed once the PR https://github.com/SAP-samples/btp-setup-automator/pull/345       has been reviewed.

**Comment by lechnerc77** [comment]
Available in Dev branch, will be part of release 1.2.0

**Comment by lechnerc77** [comment]
Close issue - [release 1.2.0](https://github.com/SAP-samples/btp-setup-automator/releases/tag/btpsa-v1.2.0) is available.
Docker Image is updated (`docker pull ghcr.io/sap-samples/btp-setup-automator:btpsa-v1.2.0`)
