### ISSUE TITLE
[BUG] Not all users are added to CF Org members

### ISSUE THREAD

**Issue by AnatolManikalo** [SAP-samples/btp-setup-automator#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Cloud Foundry setups

### Current Behavior

Some users are not added as CF Org managers: of 12 users who were supposed to be added only 8 got the actual assignment

### Expected Behavior

All users should be added 

### Steps To Reproduce

I ran the script multiple times and the result is always the same: same 8 users of 12 total are added, 4 are missing, however logs show that commands are run for all users

### Logs and configuration files available?

<img width="1707" alt="cfRoleAssignment" src="https://user-images.githubusercontent.com/32706007/206175574-72366ec1-c697-4e75-a1e1-6fdb6a7680dd.png">

**Comment by lechnerc77** [comment]
@AnatolManikalo as you ran the script several times one follow-up question: are always the same 4 users missing or is there a difference concerning the 8 users that were assigned?

**Comment by AnatolManikalo** [comment]
@lechnerc77 yes, exactly same users are added every time. Here's the result of the latest run, and same users are added (same missing :)

![image](https://user-images.githubusercontent.com/32706007/206185132-a25e3dc0-d977-4395-9f5c-ae3705419035.png)

**Comment by lechnerc77** [comment]
I just reworked the error messages forwarded in the logs. This rework is available in the `dev` branch. Can you execute your setup with the following new dev container:

```bash
docker pull ghcr.io/sap-samples/btp-setup-automator-dev:dev
```

and post the logs here. Thanks

**Comment by AnatolManikalo** [comment]
Hi @lechnerc77 

There are 2 types of error:
```

[2022-12-07 16:28:40] INFO       :  - user >sanjay.bangalore.shivanna@sap.com<
[2022-12-07 16:28:40] RUN COMMAND: cf set-org-role 'sanjay.bangalore.shivanna@sap.com' 'sapit-automator-test' 'OrgManager'
[2022-12-07 16:28:41] ERROR      : Assigning role OrgManager to user sanjay.bangalore.shivanna@sap.com in org sapit-automator-test as anatol.manikalo@sap.com...FAILED
[2022-12-07 16:28:41] ERROR      : Ambiguous user. User with username 'sanjay.bangalore.shivanna@sap.com' exists in the following origins: platformcoeproxytest-platform, sap.ids. Specify an origin to disambiguate.
```

and 

```
2022-12-07 16:28:45] INFO       :  - user >manuel.janitzek@sap.com<
[2022-12-07 16:28:45] RUN COMMAND: cf set-org-role 'manuel.janitzek@sap.com' 'sapit-automator-test' 'OrgManager'
[2022-12-07 16:28:46] ERROR      : Assigning role OrgManager to user manuel.janitzek@sap.com in org sapit-automator-test as anatol.manikalo@sap.com...FAILED
[2022-12-07 16:28:46] ERROR      : No user exists with the username 'manuel.janitzek@sap.com'.
```

For the first: is there a way to ask automator to use sap.ids by default?
For the second: should there be something similar to --create-user-if-missing parameter in BTP?

**Comment by lechnerc77** [comment]
@AnatolManikalo : The first scenario can be mitigated by using the parameter `"idp"` in the `assignrolecollections` that you can specify per rolecollection. This will be propagted to the CF CLI via the `--origin` parameter.

There is no `--create-user-if-missing` parameter for the CF CLI. Supporting the user creation would be an enhancement of the current implementation for CF roles

**Comment by hschaefer123** [comment]
Hi @lechnerc77 ,

we have the same issue with latest image.

Using DEV image we also get an error output

```
[2022-12-07 17:16:25] ERROR      : Assigning role SpaceManager to user h.schaefer@uniorg.de in org udina-newcustx-test / space services as n.kornas@uniorg.de...FAILED
[2022-12-07 17:16:25] ERROR      : Ambiguous user. User with username 'h.schaefer@uniorg.de' exists in the following origins: STZH-DEV, httpssts.windows.netc6f356f4-9364-47, sap.ids. Specify an origin to disambiguate.
```

The error is strange, because STZH-DEV is a trust in another Global Account!.

Having a look into

Extend command ```cf set-org-role"/"cf unset-org-role" with "--origin```
if there are multiple origins

I think, by default all the calls should use 
```--origin sap.default```
to avoid this and mabye making the origin param optional.

See
https://docs.cloudfoundry.org/cf-cli/getting-started.html#-manage-roles-for-users-with-identical-usernames-in-multiple-origins

>The user exists in multiple origins. Specify an origin for the requested user from: ‘uaa’, ‘other’


What do you mean?

Regards
Holger

**Comment by lechnerc77** [comment]
@hschaefer123 @AnatolManikalo here the warp up:

The handling of errors when executing `cf set-org-role` had a bug and as a consequence error where not reported back (as shown in the screenshots above). It seemed like the assignment was executed successfully, but it was not.
PR #357 fixed this behavior; errors are now propagated and displayed correctly. However, as they are now shown, you might run need to adjust your configuration files in case an "Ambiguous user" is detected that has several (IdP) origins. You can do that as of release 1.2.0 as described in the announcement of release 1.2.0 i.e., [Detail on "Support of custom IdPs in role assignment (incl. CF roles)"](https://github.com/SAP-samples/btp-setup-automator/discussions/355#discussioncomment-4330881).

Why don't we default to sap.idp? This would mean that existing working configurations might need to be adopted and we want to avoid this breaking change for existing users.

The fix to get the correct error log is available in the `dev` branch and will be available in `main` with the next release. This issue will be closed once the new release is available

**Comment by lechnerc77** [comment]
@AnatolManikalo if you want to request the "create user if not existent" functionality for CF orgs, feel free to open an [issue for an enhancement](https://github.com/SAP-samples/btp-setup-automator/issues/new?assignees=&labels=enhancement&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%3Ctitle%3E) for that

**Comment by AnatolManikalo** [comment]
Hi @lechnerc77 here it is: https://github.com/SAP-samples/btp-setup-automator/issues/360

**Comment by lechnerc77** [comment]
Fix is available in `main` and in Docker image with release 1.2.1
