### ISSUE TITLE
[BUG] Space is being created even though it's not declared

### ISSUE THREAD

**Issue by AnatolManikalo** [SAP-samples/btp-setup-automator#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Cloud Foundry setups

### Current Behavior

Cloud Foundry space "development" is being created during setup, no "cfspacename" parameter is declared

### Expected Behavior

No space should be created if no "cfspacename" parameter is declared

### Logs and configuration files available?

[spaceissue.zip](https://github.com/SAP-samples/btp-setup-automator/files/10177234/spaceissue.zip)

### Anything else?

As you can see from parameters.json file, I removed "cfspacename" line. Usecase doesn't have any space-specific services. However, space is being created anyway

**Comment by lechnerc77** [comment]
Confirm bug, see PR #359

**Comment by lechnerc77** [comment]
The bug is fixed, and the fix is available in the `dev` branch. It will be part of the next release. To omit the creation the following setting is necessary. We provide a new parameter in `parameters.json` to enable this behavior. In case you want to skip the creation of a CF space although you create a CD environment (and an org) you can set the parameter `skipcfspacecreation` to true.

The default value of the parameter is false, so all existing `parameter.json` configurations do not need to be adjusted
 
The issue will be closed once the release is published.

**Comment by lechnerc77** [comment]
Fix is available in `main` and in Docker image with release 1.2.1

**Comment by AnatolManikalo** [comment]
Hi @lechnerc77 

Please re-open this issue. When using "skipcfspacecreation": true parameter, the script fails. For some reason it skips "cf login" command and as a result all the following cf commands (e.g. cf set-org-role) are failing with:
[2022-12-28 11:29:07] ERROR      : FAILED
[2022-12-28 11:29:07] ERROR      : No API endpoint set. Use 'cf login' or 'cf api' to target an endpoint.

If I remove this parameter, everything works fine. 

Please compare the output. Without "skipcfspacecreation": true
![noskipspace](https://user-images.githubusercontent.com/32706007/209799282-77852b30-014a-40e4-8ef5-5eec4c004d99.png)

With "skipcfspacecreation": true

![skipspacecreation](https://user-images.githubusercontent.com/32706007/209799400-80cb0055-2db7-4d07-a6d4-3c4b4b123eb5.png)
![witskipspaceresult](https://user-images.githubusercontent.com/32706007/209799423-893cb1a3-b6a4-439f-8048-5dc8ae34c170.png)

**Comment by lechnerc77** [comment]
Login to CF is hidden in space creation => should be done always when a Cloud Foundry environment is created

**Comment by lechnerc77** [comment]
The missing `cf login` is fixed with PR #381 . This fix is available in the `dev` branch (incl. corresponding Docker image) and will be available in `main` with the next release.
