### ISSUE TITLE
[Feature request] error while building alpine image - switch to alpine stable

### ISSUE THREAD

**Issue by laRose00** [SAP-samples/btp-setup-automator#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Docker Image (Build or Run)

### Current Behavior

The btp-setup-automator script shuts down due to an error while building the alpine image: 
![image](https://user-images.githubusercontent.com/63709099/210748307-ad37e183-ba65-46e7-bb0d-ca2a1d4f13c6.png)

### Expected Behavior

The script runs through and builds all necessary images.

### Steps To Reproduce

I'm using VS Code and starting the script from git bash on a Windows laptop. 

### Anything else?

I looked up the alpine image and found out that you are using the "edge" version which is under constant development and might sometimes be broken (https://wiki.alpinelinux.org/wiki/Repositories). I changed the link in the docker file to "https://dl-cdn.alpinelinux.org/alpine/latest-stable/community" and then it worked for me. Maybe it would be a good idea to always use the latest-stable version?

**Comment by lechnerc77** [comment]
We check the implications of switching to the `latest-stable` as proposed. 

If you run in an issue with building the image yourself, please be aware that pre-built images of the `main` and the `dev` branch are available in the GitHub packages of this repository

**Comment by lechnerc77** [comment]
The `dev` branch now comprises the proposed change including several (minor) version upgrades. For details see also the (announcement](https://github.com/SAP-samples/btp-setup-automator/discussions/386) in GitHub Discussions.

The change will land in `main` with the next release.
