### ISSUE TITLE
[FEATURE REQUEST] Add HANA SQL Endpoint to metadata_log.json

### ISSUE THREAD

**Issue by AlexRieder** [SAP-samples/btp-setup-automator#38]
### Which area is mainly impacted

Other

### Requested Feature

I would like to have the HANA SQL Endpoint as part of the metadata_log.json

### Use Case/Scenario

As we deploy our application to the created kyma cluster we would need to have the SQL Endpoint available during deployment. Currently the value is given by the user during execution of the script. If it would be available in the mtadata_log.json we could do the deployment without user interaction. 

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by rui1610** [comment]
Where do you normally get the SQL endpoint from? Is there an API or is it something that the CF or BTP CLI can provide?

**Comment by rui1610** [comment]
I've just created a HANA instance on my trial account and executed the CF CLI to see the metadata it provides.
Is the API endpoint one of the outputs?

`3644e40c4fac:~$ cf service "hana_cloud_instance"
Showing info of service hana_cloud_instance in org cloudfoundry-btp-setup-automator-us10-87b7b1a7-1a78-4910-ab3 / space development as rui.nogueira@sap.com...

name:             hana_cloud_instance
service:          hana-cloud-trial
tags:             
plan:             hana
description:      Leverage the in-memory data processing capabilities of SAP HANA in the cloud as one simple gateway to all data.
documentation:    https://help.sap.com/viewer/p/HANA_CLOUD
dashboard:        https://hana-cockpit.cfapps.us10.hana.ondemand.com/start?host=24b1a049-d694-4c35-86a2-153549a4dae2.hana.trial-us10.hanacloud.ondemand.com&component=cockpit&port=443
service broker:   sm-hana-cloud-trial-1ce8c293-a0f4-40b1-a52e-a70f7ac4a749

Showing status of last operation from service hana_cloud_instance...

status:    create succeeded
message:   Backup not ready
started:   2022-04-03T10:31:48Z
updated:   2022-04-03T10:43:51Z

There are no bound apps for this service.

Upgrades are not supported by this broker.`

**Comment by rui1610** [comment]
Addressed with new commit https://github.com/SAP-samples/btp-setup-automator/commit/b08720f123751995eb7b392d64b6deeb8e044ec4 . Please use the collected metadata in the metadata_log.josn file to fetch the SQL endpoint.
