### ISSUE TITLE
[BUG] btp setup automator script is not interactive therefore login not possible

### ISSUE THREAD

**Issue by laRose00** [SAP-samples/btp-setup-automator#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Documentation

### Current Behavior

While running the btp setup automator script I'm asked do a cf login but the script doesn't stop to let me input my credentials. Instead it just keeps going and then throws an error that I'm not logged in.

![logonError](https://user-images.githubusercontent.com/63709099/210784576-28414926-1e01-4145-839c-84bf8ca2d4e8.png)

### Expected Behavior

The script should stop and let me put in my credentials.

### Steps To Reproduce

start the btp-setup-automator script (https://github.com/SAP-samples/btp-setup-automator/blob/main/docs/README.md#scripting-btp-setup-automator) - I'm using sso

### Logs and configuration files available?

run the btp setup automator script

### Anything else?

I fixed the issue by adding an "-i" in the command to make it interactive: 
docker exec -i --workdir "/home/user" "test01" ./btpsa \

I also had to add an "./" before the btpsa, otherwise it would not work.

**Comment by lechnerc77** [comment]
Thanks for raising the issue. The documentation is adjusted (see PR #382)
The fix is available in the dev branch and will be available in main with the next release
