### ISSUE TITLE
[BUG] Docker image not working as expected

### ISSUE THREAD

**Issue by yashika-Gulati** [SAP-samples/btp-setup-automator#482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Docker Image (Build or Run)

### Current Behavior

There is an issue with the docker container run command that is the prebuilt image : 
" docker container run --rm -it --name "btp-setup-automator" "ghcr.io/sap-samples/btp-setup-automator:latest" "
The above image is not pointing to the latest updated automator code.

If the docker image is built locally by following the below guide : 
"https://github.com/SAP-samples/btp-setup-automator/blob/main/docs/BASIC_SETUP.md#option-3-start-docker-container-with-self-built-image"
then it works fine.

Due to this issue, the mission validation for the following missions :

1. Mission : Develop a Multitenant Extension Application in SAP BTP, Kyma Runtime
    Mission Link : " https://discovery-center.cloud.sap/missiondetail/3683/3726/ " and
2. Mission : Extend a Kyma Based Multitenant Application With Day 2 Operations
    Mission Link : https://discovery-center.cloud.sap/protected/index.html#/missiondetail/3999/4206/?tab=overview

are failing in the initial steps of preparing the development environment.

### Expected Behavior

The prebuilt image should be in sync with the latest updated btp-setup-automator repository code.

**Comment by lechnerc77** [comment]
@yashika-Gulati : What exactly is missing in the pre-built image or what error messages occur when executing the image? 

Be aware that the image tagged with lates is referring to the latest stable release built upon the main branch of this repo. 
The dev branch might have additions that are not yet part of the latest stable image. 
Can you check if the error also occurs in case of using the dev image via 

```bash
docker container run --rm -it --name "btp-setup-automator" "ghcr.io/sap-samples/btp-setup-automator-dev:dev"
```

**Comment by yashika-Gulati** [comment]
I will check it and get back if it is working or not.
Thank You

**Comment by yashika-Gulati** [comment]
Hello @lechnerc77,
So I tried following the steps again for my mission using the latest image, but I was getting the following error: 
During the authentication step, I visit the url : http://localhost:18000 manually, and this url is not working and the local host refused to connect. Here are the screenshot of the errrors faced:
<img width="686" alt="docker_err" src="https://user-images.githubusercontent.com/126136256/232690126-7f4e4170-51e7-44e0-9f32-827147a61b70.png">
<img width="485" alt="docker_err2" src="https://user-images.githubusercontent.com/126136256/232690167-6128d15e-afb6-491b-bd33-321070c67952.png">

**Comment by lechnerc77** [comment]
Hi Yashika,

this is not an error of the BTP Setup Automator, but is an issue/limitation with the handling of the logon flow for Kyma. This causes issues wrt to the callback of the OIDC flow. You probably need a service user in Kyma to execute the login flow in your setup as described [here](https://github.com/SAP-samples/btp-setup-automator/blob/cc92c63afc6ac45ee6d6c12f3e88271c97f139d0/docs/FAQ.md#i-cannot-execute-kubectl-commands-after-the-kyma-runtime-got-provisioned-is-this-a-bug)

Best, Christian

**Comment by yashika-Gulati** [comment]
@lechnerc77 

It is working and the main branch is in sync with the latest update.

Thank You
