### ISSUE TITLE
[FEATURE REQUEST] Enable "Global" Environment for the whole usecase

### ISSUE THREAD

**Issue by AlexRieder** [SAP-samples/btp-setup-automator#50]
### Which area is mainly impacted

Configuration

### Requested Feature

Hi, 

I would like to collect various parameters from the user which should happen in the "executeBeforeAccountSetup" block. Once the account setup is done I would like to use the collected input in our deployment which happens in the "executeAfterAccountSetup" block. 

Thanks 
Alex

### Use Case/Scenario

We would require that feature for our kyma usecase. 

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by rui1610** [comment]
This was fixed in the pull request https://github.com/SAP-samples/btp-setup-automator/pull/52 .
You can add global env variables in the `parameters.json` file. That file already has an example on how to set them.
