### ISSUE TITLE
[FEATURE REQUEST] rewrite btpsa to be declarative 

### ISSUE THREAD

**Issue by biehlera** [SAP-samples/btp-setup-automator#500]
### Which area is mainly impacted

Docker Image (Build or Run)

### Requested Feature

Currently, the btpsa is written non-declarative CI/CD, so it cannot be used to administer the btp setup via "gitops", e.g. if you remove a user from the use case file, it will not be deleted in the BTP, the same goes for the services, etc.

The request is to rewrite the btpsa so that it is declarative.

### Use Case/Scenario

all

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by lechnerc77** [comment]
@biehlera : We have released a first version of a Terraform Provider for SAP BTP (see [Terraform registry](https://registry.terraform.io/providers/SAP/btp/latest) and [GitHub repository](https://github.com/SAP/terraform-provider-btp)). As Terraform offers a declarative approach, contains a state of your resources and supports drift detection as well as GitOps, I would recommend to switch to this offering, to fulfill your requirements. 
We are not planning to re-implement btpsa to have these capabilities. I am there fore closing this issue
