### ISSUE TITLE
[FEATURE REQUEST] Node 18 support

### ISSUE THREAD

**Issue by js1972** [SAP-samples/btp-setup-automator#542]
### Which area is mainly impacted

Docker Image (Build or Run)

### Requested Feature

When deploying my apps that require Node 18 I am receiving errors about BADENGINE. Is it possible to have it configurable for the niode engine?

### Use Case/Scenario

Deploying any node.js btp apps that require node 18.

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by lechnerc77** [comment]
We updated the base image of Alpine of our Docker Container to version 3.18. This comprises and update to Node.js to version 18.

The change is available in the `dev` branch and the corresponding Docker image. It will land in the `main` branch with the next release.
