### ISSUE TITLE
[FEATURE REQUEST] prune or tear down everything without first creating it

### ISSUE THREAD

**Issue by js1972** [SAP-samples/btp-setup-automator#543]
### Which area is mainly impacted

CLI in general

### Requested Feature

This is more of a question than an issue. Is it possible to tear down everything created in a usecase file without first creating it all.

For example...  I wish to test an app so I run btp-setup-automator to create my subaccount; services and deploy my app.
I perform testing etc and then a few days later I want to tear it all down. It seems when using the -pruneusecase option that it goes through the whole creation and setup process first. Would be awesome to skip that and instead just delete everything in the usecase file.

### Use Case/Scenario

For standing up test environments and then blowing them away several days later.

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by lechnerc77** [comment]
Hi @js1972 , the way the `btpsa` works as you described it. We are currently not planning to change this.   
In case you want to clean up the whole setup at once you can use the BTP CLI as a workaround using the `--force-delete` flag to clean up everything in one run (see [BTP CLI command reference](https://help.sap.com/docs/btp/btp-cli-command-reference/btp-delete-accounts-subaccount)).
