### ISSUE TITLE
[BUG] The usecase json config does not allow real cloudfoundry parameters

### ISSUE THREAD

**Issue by js1972** [SAP-samples/btp-setup-automator#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Cloud Foundry setups

### Current Behavior

I should be able to choose the following:
```
    {
      "name": "cloudfoundry",
      "plan": "standard",
      "category": "ENVIRONMENT"
    },
    {
      "name": "APPLICATION_RUNTIME",
      "plan": "MEMORY",
      "category": "SERVICE",
      "amount": 4
    },
```
However, the json syntax check says plan standard and APPLICATION_RUNTIME are not available. It still works if I use them but seems odd that they aren't allowed options.

### Expected Behavior

Add the above cloud foundry options to the usecase.json syntax check.

### Steps To Reproduce

Try adding cloud foundry to any usecase file where you do not want to use the free service plan

### Logs and configuration files available?

n/a

**Comment by lechnerc77** [comment]
The JSON validation is based on the available metadata exposed by different APIs of the SAP BTP and that is machine readable. You find a complete overview in the repository <https://github.com/SAP-samples/btp-service-metadata>. 
In the case of cloud foundry there is some data missing as you already reported in issue <https://github.com/SAP-samples/btp-service-metadata/issues/18>.
As soon as this is fixed the generated JSON validation for btpsa will contain the missing values you have mentioned. Please track the issue in the metadata repository mentioned above to track the progress.
