### ISSUE TITLE
[FEATURE REQUEST] SSO with custom IDP

### ISSUE THREAD

**Issue by TVSiemens** [SAP-samples/btp-setup-automator#545]
### Which area is mainly impacted

Configuration

### Requested Feature

At the moment, when SSO is configured for the BTP Setup Automator, it's only working with the SAP IDP.  In BTP CLI, there is a parameter for a custom IDP/IAS available. The feature would be a parameter that enables SSO also for BTP Global Account users with logon via custom IDP/IAS.

### Use Case/Scenario

Running BTP Setup Automator with option SSO.

### Would you like to support us?

- [ ] Yes, I would like to support you

### Anything else?

-

**Comment by lechnerc77** [comment]
The feature is available in the `dev` branch and the corresponding Docker image with PR #549.
It will be available in the `main` branch with the next release.
