### ISSUE TITLE
Custom IDP - deactivate default IDP

### ISSUE THREAD

**Issue by TVSiemens** [SAP-samples/btp-setup-automator#562]
### Which area is mainly impacted

Configuration

### Requested Feature

We'd like to make use of the use case "setup IAS" to activate our custom IDP in the subaccount. When we run this use case, the Default IDP (SAP) in the subaccount is still active. The shadow user creation is also activated. 

Logon in a subaccount should only be possible via the custom IDP. We need a feature or option to deactivate the Default IDP (SAP) when we run a use case like "setup_ias" to create a trust config for a custom IDP. 

In addition, we also need the option to deactivate the "auto-create-shadow-users" for the custom IDP tenant.

Both should be possible with the  "btp update security/trust" command.

### Use Case/Scenario

"Setup IAS" - creation of trust do custom IDP

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by lechnerc77** [comment]
@TVSiemens Thanks for the request. As you might have seen we switched the tool into maintenance mode, so we are not planning to work on feature requests (see also <https://github.com/SAP-samples/btp-setup-automator/discussions/558>). 

We are still open to contributions from the community to add features.

**Comment by lechnerc77** [comment]
@TVSiemens I close this issue as the repository will be archived.
