### ISSUE TITLE
[FEATURE REQUEST] evolve this project to a Terraform plugin

### ISSUE THREAD

**Issue by mauriciolauffer** [SAP-samples/btp-setup-automator#61]
### Which area is mainly impacted

CLI in general

### Requested Feature

It would be great if this project could evolve to a Terraform plugin, which is the de facto standard for cloud infrastructure in Infrastructure as Code (IaC).

I believe more people would be able to help as there're heaps of documentation and examples for Terraform.

https://www.terraform.io/plugin

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by rui1610** [comment]
Hi Mauricio, happy to discuss how this could be done within an open source setup. How would you do that?
I have not a lot of know how around Terraform.

**Comment by mauriciolauffer** [comment]
Hi Rui,

Lemme just start saying I've never developed a Terraform plugin before.

Terraform plugins can be create by the community and published as [Providers](https://www.terraform.io/plugin/framework/providers). You can see a list of plugins in the [Terraform Providers Registry](https://registry.terraform.io/browse/providers) page.

A great start would be the [Terraform plugin page](https://www.terraform.io/plugin) and the open source [Terraform plugin for Cloud Foundry](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry).

**Comment by rui1610** [comment]
Hi Mauricio, as this is an open source project it highly depending on the contributions from developers.
So as long as there is nobody who is able and willing to work on this, this feature request won't move forward. 
I'll definitely won't be able to drive that.

**Comment by rui1610** [comment]
Closing this feature requirement as it is beyond the scope of this repository. In addition there is currently nobody stepping up to work on this feature request.
