### ISSUE TITLE
[BUG] Existence check fails due to defaulted org in AccountMetadata

### ISSUE THREAD

**Issue by lechnerc77** [SAP-samples/btp-setup-automator#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Cloud Foundry setups

### Current Behavior

If the BTP subaccount does not have a CF environment enabled the creation of  a service instance in CF should create the environment. To check the state the code checks if an environment exists (<https://github.com/SAP-samples/btp-setup-automator/blob/main/libs/python/btp_cli.py#L256>). This method implies that the orgID in the account metadata does not exist (see <https://github.com/SAP-samples/btp-setup-automator/blob/main/libs/python/helperEnvCF.py#L30> => Check against orgid).
However, this parameter is available in the metadata due to a defaulting at <https://github.com/SAP-samples/btp-setup-automator/blob/main/libs/python/btp_cli.py#L246>.

This will cause a failure in the `helperEnvCF` as the value is NONE in case that the org is not existing,

### Expected Behavior

CF environment get created if not existing

### Steps To Reproduce

1. Start the BTP Setup Automator
2.  Use the DSAG TT 22 Usecase

**Comment by rui1610** [comment]
Confirmed the bug and will look into your PR
