### ISSUE TITLE
[BUG] SSO not working

### ISSUE THREAD

**Issue by matt1as** [SAP-samples/btp-setup-automator#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Security

### Current Behavior

I want to log on using SSO, but calling `./btpsa -loginmethod sso` still asks me for a password 

`[2022-05-01 08:01:16] WARNING    : YOU NEED TO PROVIDE YOUR BTP PASSWORD
                      Please enter your BTP password (hit Enter when done):
`

### Expected Behavior

Something similar to when using the CF or BTP CLI
`Temporary Authentication Code ( Get one at https://login.cf.us10.hana.ondemand.c
om/passcode ): `

### Steps To Reproduce

1. In the latest docker environment
2. Call `./btpsa -loginmethod sso`

**Comment by rui1610** [comment]
Is it possible that you have set the loginmethod inside your parameters.json file to "basicAuthentication"?
The parameters.json file has a higher priority than the provided parameters in the command line.

**Comment by matt1as** [comment]
Thank you, that was the issue. Shouldn't it be the other way around, that the command line have higher priority than the settings file?

**Comment by rui1610** [comment]
I've been thinking back and forth on that question. I tend to agree with you. I'll create a feature request on this and let the community participate on the discussion and the final conclusion. Please feel free to join the discussion, too.

**Comment by rui1610** [comment]
Added a new feature request here: https://github.com/SAP-samples/btp-setup-automator/issues/82
