### ISSUE TITLE
[BUG] Your login has expired when using SSO 

### ISSUE THREAD

**Issue by matt1as** [SAP-samples/btp-setup-automator#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest docker image for BTPSA?

- [X] I'm using the latest docker image for BTPSA.

### Which area is mainly impacted

Security

### Current Behavior

When authenticating with SSO I get authentication errors in the steps following the login, se log below. I have removed my subdomain, but in the terminal it was correct.

`
Connecting to CLI server at https://cpcli.cf.eu10.hana.ondemand.com...

Opening browser for authentication at: https://cpcli.cf.eu10.hana.ondemand.com/login/v2.18.0/browser/<guid>

Failed to open browser. Please authenticate manually.
Waiting for user authentication to complete (use Ctrl+C to abort)...

Login successful
We stored your configuration file at: /home/user/.config/btp/config.json

Current target:
  Global account (subdomain: <domain>)

Tips:
    Commands are executed in the current target. To change this target, use 'btp target'.
    For an explanation of the targeting mechanism, use 'btp help target'.

OK

####################################################################################################
# Get accountdetails for your global account with subdomain id ><domain><
####################################################################################################
[2022-05-02 09:20:42] INFO       : Get global account details for account with subdomain ID ><domain><
[2022-05-02 09:20:42] RUN COMMAND: btp --format json get accounts/global-account --global-account '<domain>'
####################################################################################################
# ERROR
####################################################################################################

####################################################################################################
# ERROR
####################################################################################################
Authorization failed

Your login has expired. Please log in again.

ERROR

`

### Steps To Reproduce

- Run `./btpsa` with loginmethod set to SSO in parameters.json
- Set subdomain
- Copy and paste the login URL to your web browser

### Logs and configuration files available?

```
{
  "usecasefile": "usecases/released/cap_app_launchpad.json",
  "region": "eu10",
  "globalaccount": "<domain>",
  "myemail": "mattias.e.johansson@gmail.com",
  "loginmethod": "sso",
  "subaccountname": null,
  "orgid": null,
  "cfspacename": "development",
  "suffixinstancename": null,
  "iashost": null,
  "envvariables": {
    "BTPSA_YOUR_OWN_ENV_VARIABLE1": "Hi! I'm BTPSA!",
    "BTPSA_YOUR_OWN_ENV_VARIABLE2": "How are you doing?",
    "BTPSA_YOUR_OWN_ENV_VARIABLE3": "You can use these variables in any command 
within the `executeBeforeAccountSetup` and `executeAfterAccountSetup` section by
 accessing (and manupulating) them as an OS environment variable!"
  }
}
```

**Comment by rui1610** [comment]
Will have a look later today. Thanks for reporting!

**Comment by rui1610** [comment]
Meanwhile you can test with loginmethod set to **basicAuthentication**". There is as well an option to provide your credentials via environment variables (set loginmethod to **envVariables** and set the environment variable **BTPSA_PARAM_MYEMAIL** and **BTPSA_PARAM_MYPASSWORD** properly).

**Comment by rui1610** [comment]
I can't reproduce the issue. 
Are you 100% sure you have provided the subdomain of your BTP global account?

![Untitled](https://user-images.githubusercontent.com/1716529/166202776-6750a66d-4025-4b08-9b14-bda6bfdc1b3d.jpg)

**Comment by rui1610** [comment]
Hi @matt1as , where you able to cross-check whether you are using the correct global account subdomain as shown on the picture above? Given the error message ("Authorization failed") I think that might be the root cause of your issue.

**Comment by matt1as** [comment]
Hello,

Sorry for the late reply, not on the same computer so I had to set it up again. Yes, I can confirm it's the same subaccount, see screenshot. I'm using the same email as my "Universal Identity", could that be a problem? That's the reason I cannot log on using username/password.

```
####################################################################################################
# Get accountdetails for your global account with subdomain id >mattiasjohansson<
####################################################################################################
[2022-05-03 09:16:42] INFO       : Get global account details for account with subdomain ID >mattiasjohansson<
[2022-05-03 09:16:42] RUN COMMAND: btp --format json get accounts/global-account --global-account 'mattiasjohansson'
####################################################################################################
# ERROR
####################################################################################################

####################################################################################################
# ERROR
####################################################################################################
Authorization failed

Your login has expired. Please log in again.

ERROR
```

![image](https://user-images.githubusercontent.com/2552736/166416736-053cc568-754f-4979-8307-1a3dca1899e3.png)

**Comment by rui1610** [comment]
Hi @matt1as , we just had to revoke the PR https://github.com/SAP-samples/btp-setup-automator/pull/87 as it created many unwanted behaviours which might explain your challenge as well.

Can you please fetch the most current version of the docker image for btpsa and see, whether you still face the issue?

Let me know what the result was.

**Comment by matt1as** [comment]
Yes, I get the same issues. I also tried with an incognito Chrome just to make sure my corproate- and private BTP accounts did not get mixed up.

I do use the same email address as "Universal ID", I do not know if that might mix things up

![image](https://user-images.githubusercontent.com/2552736/166448363-e3e99bad-59ce-4834-933a-072f72a43c83.png)

**Comment by rui1610** [comment]
Have you tried in the container image the command, that the btp-setup-automator tells you, that it will execute?

In essence this command:

`btp --format json get accounts/global-account --global-account 'mattiasjohansson'`

With that you are calling the btp cli directly.

Can you share what the response is? It should be a rather lengthy json file with all details of your global-account. Maybe someone like @mgradl from the btp cli team has an idea what might be wrong.

**Comment by matt1as** [comment]
I actually get the same result if I run the BTP CLI directly on my Mac. I need to investigate this, but we can close the ticket since it's not related to the setup automator. The following is running directly on my laptop and not in the docker image.

```
Mattiass-MacBook-Pro:darwin-amd64 mattias$ ./btp login --sso
SAP BTP command line interface (client v2.18.0)

CLI server URL [https://cpcli.cf.eu10.hana.ondemand.com]>
Connecting to CLI server at https://cpcli.cf.eu10.hana.ondemand.com...

Global account subdomain [mattiasjohansson]>

Opening browser for authentication at: https://cpcli.cf.eu10.hana.ondemand.com/login/v2.18.0/browser/765db93f-f3e2-4b00-b892-3dec815511f3
Waiting for user authentication to complete (use Ctrl+C to abort)...

Login successful
We stored your configuration file at: /Users/mattias/Library/Application Support/.btp/config.json

Current target:
  Global account (subdomain: mattiasjohansson)

Tips:
    Commands are executed in the current target. To change this target, use 'btp target'.
    For an explanation of the targeting mechanism, use 'btp help target'.

OK

Mattiass-MacBook-Pro:darwin-amd64 mattias$ ./btp list security/roles
Authorization failed

Your login has expired. Please log in again.

ERROR

Mattiass-MacBook-Pro:darwin-amd64 mattias$ ./btp logout
There was no active login - you are logged out.

OK

Mattiass-MacBook-Pro:darwin-amd64 mattias$ 

```
