### ISSUE TITLE
[FEATURE REQUEST] give command line parameters higher priority than the ones in parameters.json file

### ISSUE THREAD

**Issue by rui1610** [SAP-samples/btp-setup-automator#82]
### Which area is mainly impacted

Configuration

### Requested Feature

Currently the parameters defined in the parameters.json file have a higher priority than the ones provided via command line. This behaviours should be turned around.

### Use Case/Scenario

Take the issue https://github.com/SAP-samples/btp-setup-automator/issues/77 as a basis. The user provided a parameter via the command line, but that one was over-ruled by the respective parameter in the parameters.json file.

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by veichtj** [comment]
@rui1610 - I would also support this feature as it would make the usage more intuitive, usually command line parameters overwrite everything that is defines somewhere else.

**Comment by rui1610** [comment]
Hi @veichtj  and @matt1as , thanks for your input. 

@lechnerc77 was kind enough to deliver a pull request that I've just merged.

The new docker image should be there within the next 5 minutes.
