### ISSUE TITLE
[rl-assigned_teams-1] At least two teams (admins, members) need to be assigned to a repository

### ISSUE THREAD

**Issue by rui1610** [SAP-samples/btp-setup-automator#85]
This issue was generated by the SAP Repository Linter. It checks repositories for their compliance with the SAP open source project guidelines. As an SAP employee you can see further details at https://wiki.wdf.sap.corp/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-AssignedTeams(rl-assigned_teams-XX)

**Comment by ajinkyapatil8190** [comment]
![image](https://user-images.githubusercontent.com/13133800/166253374-1a382f17-7490-45d2-adda-362af21c7959.png)
Completed. I marked you as the maintainer for the new team and I also added some colleagues from the previously existing team, if you want you can add more colleagues 👍
